networks:
  proxy_default:
    external: true
    name: "proxy_default"

services:
  proxy-ddns-1:
    container_name: "proxy-ddns-1"
    entrypoint:
      - "dotnet"
      - "DDNSUpdater.dll"
    environment:
      - "LogLevel=Debug"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "ASPNETCORE_URLS=http://+:80"
      - "DOTNET_RUNNING_IN_CONTAINER=true"
      - "DOTNET_VERSION=7.0.10"
    hostname: "f77702ae8ab8"
    image: "saile2204/ddns:latest"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "0f64bf8103fe0f71aa94701706ebb5694e620989dabd12c408f207bbbaf98537"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:d28ed4e32a11c59903b2a3e265f29a3577be3479e3c23b829577b48487cd747b"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "proxy"
      com.docker.compose.project.config_files: "/root/Proxy/docker-compose.yml"
      com.docker.compose.project.working_dir: "/root/Proxy"
      com.docker.compose.service: "ddns"
      com.docker.compose.version: "2.20.2"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "proxy_default"
    restart: "unless-stopped"
    stdin_open: true
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/app"

version: "3.6"
